databases:
  - name: django_on_render
    user: admin
    plan: free
    region: frankfurt

services:
  - type: web
    name: django_on_render
    plan: free
    region: frankfurt
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./venv/bin/python -m gunicorn -b :8000 django_on_render.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_on_render
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: POETRY_VERSION
        value: 1.5.1
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ADMIN_LOGIN
        value: admin
      - key: DJANGO_ADMIN_PASSWORD
        generateValue: true
      - key: DJANGO_ADMIN_EMAIL
        value: admin@bluelake.fr
